[nfs]
172.31.17.109 ansible_ssh_user='ec2-user'

[webservers]
172.31.19.166 ansible_ssh_user='ec2-user'
172.31.17.83 ansible_ssh_user='ec2-user'

[db]
172.31.22.201 ansible_ssh_user='ec2-user' 

[lb]
172.31.16.244 ansible_ssh_user='ubuntu'